package org.fun;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.fun.data.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.Banner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@SpringBootApplication
@ComponentScan(basePackages = "org.fun")
public class App {
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private ObjectMapper json;

    public static void main(String[] args) {
        SpringApplication authApplication = new SpringApplication(App.class);
        authApplication.setBannerMode(Banner.Mode.OFF);
        authApplication.run(args);
    }
}
